=== TonyMalz/EMI/teilleistung_2/autohaus.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT wagenbestand (wagen*)>
<!ELEMENT wagen (hersteller, modell, baujahr, erstzulassung, km, neuwagen?, antriebsart, motor, unfall*, url?, karosserieform)>
<!ATTLIST wagen
    WagenID ID #REQUIRED
>
<!ELEMENT km (#PCDATA)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT tank (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT motor (verbrennung | elektro)>
<!ELEMENT modell (#PCDATA)>
<!ELEMENT unfall (date, beschreibung)>
<!ELEMENT baujahr (#PCDATA)>
<!ELEMENT neuwagen EMPTY>
<!ELEMENT hersteller (#PCDATA)>
<!ELEMENT antriebsart EMPTY>
<!ATTLIST antriebsart
    typ (Front | Heck | Allrad) #REQUIRED
>
<!ELEMENT verbrennung (ps, tank)>
<!ATTLIST verbrennung
    typ (Benzin | Diesel) #REQUIRED
>
<!ELEMENT elektro (ps, akkukapazitaet)>
<!ATTLIST elektro
    typ CDATA #FIXED "Elektro"
>
<!ELEMENT akkukapazitaet (#PCDATA)>
<!ELEMENT beschreibung (#PCDATA)>
<!ELEMENT erstzulassung (date | none)>
<!ELEMENT date (day, month, year)>
<!ELEMENT none EMPTY>
<!ELEMENT karosserieform EMPTY>
<!ATTLIST karosserieform
    typ (Limousine | Coupe | Kombi | Cabriolet | sonstige) #REQUIRED
>

=== TonyMalz/EMI/teilleistung_2/autohaus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wagenbestand SYSTEM "autohaus.dtd">
<?xml-stylesheet type="text/xsl" href="autohaus.xsl"?>
<wagenbestand>
	<wagen WagenID="1">
		<hersteller>Porsche</hersteller>
		<modell>911 Carrera 4s</modell>
		<baujahr>2012</baujahr>
		<erstzulassung>
			<day>12</day>
			<month>12</month>
			<year>2012</year>
		</erstzulassung>
		<km>12500</km>
		<antriebsart typ="Allrad"/>
		<motor>
			<verbrennung typ="Benzin">
				<ps>345</ps>
				<tank>67</tank>
			</verbrennung>
		</motor>
		<unfall>
			<day>24</day>
			<month>12</month>
			<year>2012</year>
			<beschreibung>Boom hat's gmacht...</beschreibung>
		</unfall>
		<unfall>
			<day>02</day>
			<month>11</month>
			<year>2012</year>
			<beschreibung>Frontal-Crash</beschreibung>
		</unfall>
		<url>img/carrera4s.jpeg</url>
		<karosserieform typ="Coupe"/>
	</wagen>
	<wagen WagenID="2">
		<hersteller>Porsche</hersteller>
		<modell>Cayenne</modell>
		<baujahr>2013</baujahr>
		<erstzulassung/>
		<km>0</km>
		<neuwagen/>
		<antriebsart typ="Allrad"/>
		<motor>
			<verbrennung typ="Diesel">
				<ps>200</ps>
				<tank>80</tank>
			</verbrennung>
		</motor>
		<url>img/cayenne.jpeg</url>
		<karosserieform typ="sonstige"/>
	</wagen>
	<wagen WagenID="3">
		<hersteller>Porsche</hersteller>
		<modell>Cayman S</modell>
		<baujahr>2013</baujahr>
		<erstzulassung/>
		<km>0</km>
		<neuwagen/>
		<antriebsart typ="Heck"/>
		<motor>
			<verbrennung typ="Benzin">
				<ps>330</ps>
				<tank>67</tank>
			</verbrennung>
		</motor>
		<url>img/cayman.jpeg</url>
		<karosserieform typ="Coupe"/>
	</wagen>
	<wagen WagenID="4">
		<hersteller>Porsche</hersteller>
		<modell>911 Turbo</modell>
		<baujahr>2014</baujahr>
		<erstzulassung />
		<km>0</km>
		<neuwagen/>
		<antriebsart typ="Allrad"/>
		<motor>
			<verbrennung typ="Benzin">
				<ps>450</ps>
				<tank>80</tank>
			</verbrennung>
		</motor>
		<url>img/turbo.jpeg</url>
		<karosserieform typ="Coupe"/>
	</wagen>
	<wagen WagenID="5">
		<hersteller>BMW</hersteller>
		<modell>330i</modell>
		<baujahr>2011</baujahr>
		<erstzulassung>
			<day>14</day>
			<month>02</month>
			<year>2010</year>
		</erstzulassung>
		<km>12789</km>
		<antriebsart typ="Heck"/>
		<motor>
			<verbrennung typ="Benzin">
				<ps>330</ps>
				<tank>60</tank>
			</verbrennung>
		</motor>
		<url>img/330i.jpeg</url>
		<karosserieform typ="Limousine"/>
	</wagen>
	<wagen WagenID="6">
		<hersteller>BMW</hersteller>
		<modell>330d</modell>
		<baujahr>2010</baujahr>
		<erstzulassung>
			<day>01</day>
			<month>02</month>
			<year>2010</year>
		</erstzulassung>
		<km>227349</km>
		<antriebsart typ="Heck"/>
		<motor>
			<verbrennung typ="Diesel">
				<ps>230</ps>
				<tank>60</tank>
			</verbrennung>
		</motor>
		<karosserieform typ="Limousine"/>
	</wagen>
	<wagen WagenID="7">
		<hersteller>Tesla</hersteller>
		<modell>Model S</modell>
		<baujahr>2014</baujahr>
		<erstzulassung>
			<day>11</day>
			<month>03</month>
			<year>2014</year>
		</erstzulassung>
		<km>300</km>
		<antriebsart typ="Heck"/>
		<motor>
			<elektro typ="Elektro">
				<ps>400</ps>
				<akkukapazitaet>85</akkukapazitaet>
			</elektro>
		</motor>
		<unfall>
			<day>02</day>
			<month>4</month>
			<year>2014</year>
			<beschreibung>Batterie explodiert!</beschreibung>
		</unfall>
		<url>img/tesla_s.jpeg</url>
		<karosserieform typ="Coupe"/>
	</wagen>
	<wagen WagenID="8">
		<hersteller>Tesla</hersteller>
		<modell>Roadster</modell>
		<baujahr>2014</baujahr>
		<erstzulassung />
		<km>0</km>
		<neuwagen/>
		<antriebsart typ="Heck"/>
		<motor>
			<elektro typ="Elektro">
				<ps>500</ps>
				<akkukapazitaet>85</akkukapazitaet>
			</elektro>
		</motor>
		<url>img/tesla_r.jpeg</url>
		<karosserieform typ="Coupe"/>
	</wagen>
	<wagen WagenID="9">
		<hersteller>VW</hersteller>
		<modell>Golf</modell>
		<baujahr>2014</baujahr>
		<erstzulassung />
		<km>0</km>
		<neuwagen/>
		<antriebsart typ="Front"/>
		<motor>
			<verbrennung typ="Benzin">
				<ps>110</ps>
				<tank>85</tank>
			</verbrennung>
		</motor>
		<url>img/golf.jpeg</url>
		<karosserieform typ="Limousine"/>
	</wagen>
	<wagen WagenID="10">
		<hersteller>VW</hersteller>
		<modell>Golf Kombi</modell>
		<baujahr>2012</baujahr>
		<erstzulassung>
			<day>02</day>
			<month>08</month>
			<year>2012</year>
		</erstzulassung>
		<km>10331</km>
		<antriebsart typ="Front"/>
		<motor>
			<verbrennung typ="Diesel">
				<ps>95</ps>
				<tank>85</tank>
			</verbrennung>
		</motor>
		<url>img/golf_kombi.jpeg</url>
		<karosserieform typ="Kombi"/>
	</wagen>
	<wagen WagenID="10">
		<hersteller>Mercedes</hersteller>
		<modell>SLK</modell>
		<baujahr>2009</baujahr>
		<erstzulassung>
			<day>02</day>
			<month>08</month>
			<year>2009</year>
		</erstzulassung>
		<km>14331</km>
		<antriebsart typ="Heck"/>
		<motor>
			<verbrennung typ="Benzin">
				<ps>330</ps>
				<tank>75</tank>
			</verbrennung>
		</motor>
		<karosserieform typ="Coupe"/>
	</wagen>
</wagenbestand>
