=== TonyMalz/EMI/teilleistung_2/tl2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT wagenbestand (wagen*)>
<!ELEMENT km (#PCDATA)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT tank (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT motor (verbrennung | elektro)>
<!ELEMENT wagen (hersteller, modell, baujahr, erstzulassung, km, neuwagen?, antriebsart, motor, unfall*, url?, karosserieform)>
<!ATTLIST wagen
	WagenID ID #REQUIRED
>
<!ELEMENT modell (#PCDATA)>
<!ELEMENT unfall (day, month, year, beschreibung)>
<!ELEMENT baujahr (#PCDATA)>
<!ELEMENT neuwagen EMPTY>
<!ELEMENT hersteller (#PCDATA)>
<!ELEMENT antriebsart EMPTY>
<!ATTLIST antriebsart
	typ (Front | Heck | Allrad) #REQUIRED
>
<!ELEMENT verbrennung (ps, tank)>
<!ATTLIST verbrennung
	typ (Benzin | Diesel) #REQUIRED
>
<!ELEMENT elektro (ps, akkukapazitaet)>
<!ELEMENT akkukapazitaet (#PCDATA)>
<!ELEMENT beschreibung (#PCDATA)>
<!ELEMENT erstzulassung (day, month, year)>
<!ELEMENT karosserieform EMPTY>
<!ATTLIST karosserieform
	typ (Limousine | Coupe | Kombi | Cabriolet | sonstige) #REQUIRED
>

=== TonyMalz/EMI/teilleistung_2/tl2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wagenbestand SYSTEM "tl2.dtd">
<?xml-stylesheet type="text/xsl" href="tl3.xsl"?>
<wagenbestand>
	<wagen WagenID="asb1234">
		<hersteller>Porsche</hersteller>
		<modell>Carrera 4s</modell>
		<baujahr>2012</baujahr>
		<erstzulassung>
			<day>12</day>
			<month>12</month>
			<year>1979</year>
		</erstzulassung>
		<km>12500</km>
		<antriebsart typ="Allrad"/>
		<motor>
			<verbrennung typ="Benzin">
				<ps>345</ps>
				<tank>67</tank>
			</verbrennung>
		</motor>
		<unfall>
			<day>56</day>
			<month>34</month>
			<year>1232</year>
			<beschreibung>Boom hat's gmacht...</beschreibung>
		</unfall>
		<url>img2.jpg</url>
		<karosserieform typ="Coupe"/>
	</wagen>
	<wagen WagenID="asb12334">
		<hersteller>Porsche</hersteller>
		<modell>Cayenne</modell>
		<baujahr>2012</baujahr>
		<erstzulassung>
			<day>12</day>
			<month>12</month>
			<year>1979</year>
		</erstzulassung>
		<km>12500</km>
		<neuwagen/>
		<antriebsart typ="Allrad"/>
		<motor>
			<verbrennung typ="Diesel">
				<ps>345</ps>
				<tank>80</tank>
			</verbrennung>
		</motor>
		<url>img2.jpg</url>
		<karosserieform typ="sonstige"/>
	</wagen>
</wagenbestand>
